apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
  name: mygroup
spec:
  clusterDeploymentRefs:
  - name: kind-cluster1
  resourceApplyMode: Upsert
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-monitoring
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: cluster-monitoring-config
      namespace: openshift-monitoring
